apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nw.pubsub.jobs
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: 0.0.0.0:6379
  - name: redisPassword
    value: ""